[tool.briefcase]
project_name = "BlueShare"
bundle = "com.vinaypanchal"
version = "0.0.1"
url = "https://vinaypanchal.com/blueshare"
license = "Proprietary"
author = 'Vinay Panchal'
author_email = "vinay.npanchal@gmail.com"

[tool.briefcase.app.blueshare]
formal_name = "BlueShare"
description = "Share files using bluetooth"
icon = "src/blueshare/resources/blueshare"
sources = ['src/blueshare']
requires = []


[tool.briefcase.app.blueshare.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.blueshare.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.blueshare.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.blueshare.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.blueshare.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
